Document: sambaedu-client-windows
Title: Debian sambaedu-client-windows Manual
Author: <insert document author here>
Abstract: This manual describes what sambaedu-client-windows is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sambaedu-client-windows/sambaedu-client-windows.sgml.gz

Format: postscript
Files: /usr/share/doc/sambaedu-client-windows/sambaedu-client-windows.ps.gz

Format: text
Files: /usr/share/doc/sambaedu-client-windows/sambaedu-client-windows.text.gz

Format: HTML
Index: /usr/share/doc/sambaedu-client-windows/html/index.html
Files: /usr/share/doc/sambaedu-client-windows/html/*.html
